const annotationsData = {

    "cropLimitToImage": true,
    "cropMinSize": {
        "width": 1,
        "height": 1
    },
    "cropMaxSize": {
        "width": 32768,
        "height": 32768
    },
    "flipX": false,
    "flipY": false,
    "rotation": 0,
    "manipulation": [],
    "redaction": [],
    "annotation": [
        {
            "x": "-0.93%",
            "y": "58.24%",
            "width": "123.69%",
            "height": "93.29%",
            "strokeColor": [
                1,
                1,
                1,
                0
            ],
            "backgroundColor": [
                0.4000000059604645,
                0.929411768913269,
                0.8470588326454163,
                1
            ],
            "backgroundColorHex": "#66edd8",
            "cornerRadius": 0,
            "strokeWidth": 0,
            "rotation": -0.006782948303725088,
            "rotationDegrees": -0.38863431045886837,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "Rectangle 4",
            "disableErase": true,
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "43.98%",
            "y": "31.02%",
            "width": "6.57%",
            "height": "4.72%",
            "backgroundImage": "https://fluiditytech.blob.core.windows.net/common-media/8325994d-9d36-400c-aabb-1d261fae1f86.246c31cdf0458301650eb66704e33efc.png?se=2030-09-10T19%3A42%3A12Z&sp=r&sv=2025-01-05&sr=b&sig=UyzV%2Bay0wz6%2BFsFWfkrT7BmDFcf84iYcMRYToPrqqro%3D",
            "format": "image",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "Clip path group (7) 1",
            "disableErase": true,
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "0.00%",
            "y": "27.13%",
            "width": "40.83%",
            "height": "41.02%",
            "backgroundImage": "https://fluiditytech.blob.core.windows.net/common-media/36682992-abf0-42fb-845e-a0b989ef6105.18528a793cf28b06e3af611f093bec06.png?se=2030-09-10T19%3A42%3A16Z&sp=r&sv=2025-01-05&sr=b&sig=HSyBK/TqUxD/NNXk9/iNq96Mr5/AN7ze7MMumRjWJpU%3D",
            "format": "image",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "Clip path group (1) 1",
            "disableErase": true,
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "44.63%",
            "y": "35.74%",
            "width": "13.33%",
            "height": "38.52%",
            "backgroundImage": "https://fluiditytech.blob.core.windows.net/common-media/431682c3-c5ba-47c1-9c48-e88e0399fc49.622295a724615e2508e44981ce27b153.png?se=2030-09-10T19%3A42%3A20Z&sp=r&sv=2025-01-05&sr=b&sig=/c0PVtXZ%2BJxpr8T%2BFgIF50EqVYNDSaTM/zkOhBmH4hw%3D",
            "format": "image",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "Clip path group (6) 1",
            "disableErase": true,
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "51.76%",
            "y": "36.11%",
            "width": "28.81%",
            "height": "37.75%",
            "backgroundImage": "https://fluiditytech.blob.core.windows.net/common-media/0b1414a1-9abc-4bff-a728-c89543cbf96f.28d4a03cf2117a560a9d34e9983cbd21.png?se=2030-09-10T19%3A42%3A24Z&sp=r&sv=2025-01-05&sr=b&sig=QdUJxlWYbcsCjI1Wf8VfueKWuZjOXnjRv5oMAqnbtqI%3D",
            "format": "image",
            "rotation": 0.0035798356691883653,
            "rotationDegrees": 0.2051094751948841,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "product_image",
            "disableErase": true,
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "34.81%",
            "y": "49.81%",
            "width": "44.81%",
            "height": "39.26%",
            "backgroundImage": "https://fluiditytech.blob.core.windows.net/common-media/ba779148-ec51-4335-831a-d109edad65f3.192ffefbedde0de2568c0fc07d9b755c.png?se=2030-09-10T19%3A42%3A29Z&sp=r&sv=2025-01-05&sr=b&sig=whdo5thlUKF%2B5X9lkASQinc%2B1gFe0jDkMzCP3U3YJsI%3D",
            "format": "image",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "Clip path group (3) 1",
            "disableErase": true,
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "11.20%",
            "y": "4.35%",
            "width": "77.59%",
            "height": "15.56%",
            "text": "ENERGY WITHOUT ",
            "disableTextScale": true,
            "color": [
                1.0,
                1.0,
                1.0,
                1
            ],
            "colorHex": "#ffffff",
            "fontSize": 96.0,
            "fontFamily": "Kanit",
            "lineHeight": "120%",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "heading_text_1",
            "disableErase": true,
            "fontVariant": "normal",
            "format": "text",
            "textAlign": "CENTER",
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "21.94%",
            "y": "12.13%",
            "width": "52.50%",
            "height": "15.56%",
            "text": "THE JITTERS",
            "disableTextScale": true,
            "color": [
                1.0,
                1.0,
                1.0,
                1
            ],
            "colorHex": "#ffffff",
            "fontSize": 96.0,
            "fontFamily": "Kanit",
            "lineHeight": "120%",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "heading_text_2",
            "disableErase": true,
            "fontVariant": "normal",
            "format": "text",
            "textAlign": "CENTER",
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "79.72%",
            "y": "38.52%",
            "width": "9.07%",
            "height": "6.57%",
            "backgroundImage": "https://fluiditytech.blob.core.windows.net/common-media/8f5b23ad-c4ea-4a63-aa8d-405dc62bcf20.db8416231191c081b990166889b27416.png?se=2030-09-10T19%3A42%3A32Z&sp=r&sv=2025-01-05&sr=b&sig=G8sf/FKXKA7YZVbIKYU4FGJpKi4aP9tZhn5BQ0ozmgU%3D",
            "format": "image",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "Clip path group (4) 1",
            "disableErase": true,
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "81.02%",
            "y": "45.37%",
            "width": "18.43%",
            "height": "6.48%",
            "text": "30-DAY",
            "disableTextScale": true,
            "color": [
                0.6274510025978088,
                0.9607843160629272,
                0.9137254953384399,
                1
            ],
            "colorHex": "#a0f5e9",
            "fontSize": 47.0,
            "fontFamily": "Kanit",
            "lineHeight": "120%",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "text2",
            "disableErase": true,
            "fontVariant": "normal",
            "format": "text",
            "textAlign": "CENTER",
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "33.43%",
            "y": "31.67%",
            "width": "10.56%",
            "height": "6.48%",
            "text": "FREE",
            "disableTextScale": true,
            "color": [
                0.6274510025978088,
                0.9607843160629272,
                0.9137254953384399,
                1
            ],
            "colorHex": "#a0f5e9",
            "fontSize": 47.0,
            "fontFamily": "Kanit",
            "lineHeight": "120%",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "text1",
            "disableErase": true,
            "fontVariant": "normal",
            "format": "text",
            "textAlign": "CENTER",
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "13.24%",
            "y": "65.83%",
            "width": "18.43%",
            "height": "6.48%",
            "text": "2000MG",
            "disableTextScale": true,
            "color": [
                0.6274510025978088,
                0.9607843160629272,
                0.9137254953384399,
                1
            ],
            "colorHex": "#a0f5e9",
            "fontSize": 47.0,
            "fontFamily": "Kanit",
            "lineHeight": "120%",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "text3",
            "disableErase": true,
            "fontVariant": "normal",
            "format": "text",
            "textAlign": "CENTER",
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "74.44%",
            "y": "51.85%",
            "width": "27.96%",
            "height": "6.39%",
            "text": "MONEY-BACK\n",
            "disableTextScale": true,
            "color": [
                0.9966863393783569,
                0.9966863393783569,
                0.9966863393783569,
                1
            ],
            "colorHex": "#fefefe",
            "fontSize": 32.0,
            "fontFamily": "Kanit",
            "lineHeight": "120%",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "text2_sub1",
            "disableErase": true,
            "fontVariant": "normal",
            "format": "text",
            "textAlign": "CENTER",
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "7.96%",
            "y": "71.67%",
            "width": "27.96%",
            "height": "6.39%",
            "text": "ADAPTOGENIC\n",
            "disableTextScale": true,
            "color": [
                0.9966863393783569,
                0.9966863393783569,
                0.9966863393783569,
                1
            ],
            "colorHex": "#fefefe",
            "fontSize": 32.0,
            "fontFamily": "Kanit",
            "lineHeight": "120%",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "text3_sub1",
            "disableErase": true,
            "fontVariant": "normal",
            "format": "text",
            "textAlign": "CENTER",
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "25.00%",
            "y": "37.04%",
            "width": "27.96%",
            "height": "6.39%",
            "text": "STIRRING",
            "disableTextScale": true,
            "color": [
                0.9966863393783569,
                0.9966863393783569,
                0.9966863393783569,
                1
            ],
            "colorHex": "#fefefe",
            "fontSize": 32.0,
            "fontFamily": "Kanit",
            "lineHeight": "120%",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "text1_sub1",
            "disableErase": true,
            "fontVariant": "normal",
            "format": "text",
            "textAlign": "CENTER",
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "76.30%",
            "y": "55.37%",
            "width": "24.91%",
            "height": "4.44%",
            "text": "GAURANTEE",
            "disableTextScale": true,
            "color": [
                1.0,
                1.0,
                1.0,
                1
            ],
            "colorHex": "#ffffff",
            "fontSize": 32.0,
            "fontFamily": "Kanit",
            "lineHeight": "120%",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "text2_sub2",
            "disableErase": true,
            "fontVariant": "normal",
            "format": "text",
            "textAlign": "CENTER",
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "9.91%",
            "y": "74.91%",
            "width": "24.91%",
            "height": "4.44%",
            "text": "MUSHROOMS",
            "disableTextScale": true,
            "color": [
                1.0,
                1.0,
                1.0,
                1
            ],
            "colorHex": "#ffffff",
            "fontSize": 32.0,
            "fontFamily": "Kanit",
            "lineHeight": "120%",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "text3_sub2",
            "disableErase": true,
            "fontVariant": "normal",
            "format": "text",
            "textAlign": "CENTER",
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "26.39%",
            "y": "40.19%",
            "width": "24.91%",
            "height": "4.44%",
            "text": "SPOON",
            "disableTextScale": true,
            "color": [
                1.0,
                1.0,
                1.0,
                1
            ],
            "colorHex": "#ffffff",
            "fontSize": 32.0,
            "fontFamily": "Kanit",
            "lineHeight": "120%",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "text1_sub2",
            "disableErase": true,
            "fontVariant": "normal",
            "format": "text",
            "textAlign": "CENTER",
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "32.50%",
            "y": "69.07%",
            "width": "12.87%",
            "height": "4.91%",
            "backgroundImage": "https://fluiditytech.blob.core.windows.net/common-media/680fd264-2219-4138-a67d-cff7af8cd3d0.8e4eb0e0eeee7ef7a5a13089000b6337.png?se=2030-09-10T19%3A42%3A36Z&sp=r&sv=2025-01-05&sr=b&sig=jrKpY6jXaRxhwumfm8go/qQ0jyaRV6dcQIjilFYax08%3D",
            "format": "image",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "Clip path group (5) 1",
            "disableErase": true,
            "isSelected": false,
            "isEditing": false
        },
        {
            "x": "57.41%",
            "y": "92.31%",
            "width": "38.98%",
            "height": "7.13%",
            "text": "JUST $1 PER CUP",
            "disableTextScale": true,
            "color": [
                0.6352941393852234,
                0.18039216101169586,
                0.6823529601097107,
                1
            ],
            "colorHex": "#a22eae",
            "fontSize": 50.0,
            "fontFamily": "Kanit",
            "lineHeight": "120%",
            "rotation": 0.0,
            "rotationDegrees": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "id": "pricing_text",
            "disableErase": true,
            "fontVariant": "normal",
            "format": "text",
            "textAlign": "CENTER",
            "isSelected": false,
            "isEditing": false
        }
    ],
    "decoration": [],
    "selection": [],
    "backgroundColor": [
        0.9334183931350708,
        0.12500935792922974,
        0.8660511374473572,
        1
    ],
    "volume": 1,
    "crop": {
        "x": 0,
        "y": 0,
        "width": 1080.0,
        "height": 1080.0
    },
    "backgroundColorHex": "#ee1fdc",
};


export default annotationsData;